# Copyright (C) 2013 Rotzloch (roland.vonrotz@gmail.com)
name: MaRo-Craft
author: Rotzloch
main: me.rotzloch.main.MaRoCraft
version: 1.0
depend: [Vault, WorldEdit, WorldGuard]
commands:
  land:
    description: Hauptbefehl fuer GSManagement
    usage: Gib /land help ein, um mehr Informationen zu bekommen.
  farm:
    description: Hauptbefehl fuer Farmonator
    usage: /farm help